#ifndef _SYSCALL_NUMBER_H_
#define _SYSCALL_NUMBER_H_

#define BACKTOSV_SVC_NUMBER 1
#define SLEEP_SVC_NUMBER 2
#define GET_TICKS_SVC_NUMBER 3
#define SBRK_SVC_NUMBER 4
#define REGISTER_FIFO_SVC_NUMBER 5
#define UNREGISTER_FIFO_SVC_NUMBER 6

#endif