#ifndef _SYSCALL_NUMBER_H_
#define _SYSCALL_NUMBER_H_

#define GET_PID_SVC_NUMBER 1
#define SLEEP_SVC_NUMBER 2
#define GET_TICKS_SVC_NUMBER 3
#define SBRK_SVC_NUMBER 4
#define REGISTER_FIFO_SVC_NUMBER 5
#define UNREGISTER_FIFO_SVC_NUMBER 6
#define ATTACH_FIFO_SVC_NUMBER 7
#define SEND_SVC_NUMBER 8
#define RECEIVE_SVC_NUMBER 9
#define WRITE_FIFO_SVC_NUMBER 10
#define READ_FIFO_SVC_NUMBER 11

#endif